config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :customers
  root 'customers#index'
  resources :comments, only: [:create, :destroy]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :customer
  belongs_to :user
  
  validates :body,        presence: true, length: { maximum: 200 } 
  validates :customer_id, presence: true
end

app/models/company.rb
class Company < ActiveRecord::Base
    has_many :customers
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :company
  belongs_to :post
  has_many :comments
  
  validates :family_name,
    presence: true, length: { maximum: 20 }
  validates :given_name,
    presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
    presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  
  validates :company_id, presence: true
  validates :post_id, presence: true
  
  def full_name
    family_name + given_name
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :customers
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:family_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:given_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:image_url])
    devise_parameter_sanitizer.permit(:account_update, keys: [:family_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:given_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:image_url])
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index

  end

  def show

  end

  def new

  end

  def create
   @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to customer_path(@comment.customer_id)
    else
      @customer = @comment.customer
      @comments = @customer.comments
      render template: "customers/show"
    end
    
    
  end

  def edit

  end

  def update

  end

  def destroy
   @comment = Comment.find(params[:id])
   customer_id = @comment.customer_id
   @comment.destroy
   redirect_to customer_path(customer_id)
  end
  
  private
  
  def comment_params
      params.require(:comment).permit(:body, :customer_id, :user_id)
  end
  
  
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!, only: [ :show, :index, :new, :create, :edit, :update, :destroy]
  before_action :set_customer, only: [ :show, :edit, :update, :destroy ]
  
  def index
    @q = Customer.search(params[:q])
    @customers = @q.result(distinct: true).page(params[:page])
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
     redirect_to @customer
    else
     render :new
    end
  end

  def edit
    
  end

  def update
    if  @customer.update(customer_params)
      redirect_to @customer
    else
      render :edit
    end
  end

  def show
    @comment = Comment.new
    @comments = @customer.comments
  end

  def destroy
    @customer.destroy
    redirect_to root_path
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(
      :family_name,
      :given_name,
      :email,
      :company_id,
      :post_id
      )
  end
  
  def set_customer
      @customer = Customer.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>

 <% if @customer.errors.any? %>
    <div class="alert alert-danger">
      <p><b><%= @customer.errors.count %>件のエラーがあります</b></p>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :family_name %><br>
    <%= f.text_field :family_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :given_name %><br>
    <%= f.text_field :given_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: "form-control" %>
  
  <div class="form-group">
    <%= f.label :company_id %>
    <%= f.collection_select :company_id, Company.all, :id, :name , { include_blank: "会社を選択してください" },  { class: "form-control" } %>
  </div>
  
  <div class="form-group">
    <%= f.label :post_id %>
    <%= f.collection_select :post_id, Post.all, :id, :position_name, { include_blank: "役職を選択してください" }, { class: "form-control" } %>
  </div>  
    
  </div>
  <%= f.submit class: "btn btn-default" %>
<% end %>

app/views/customers/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>顧客情報の編集</h1>
    <%= render 'form' %>
    <button type="button" style="margin-top:5px;" class="btn btn-default" data-toggle="modal" data-target="#delete-customer">顧客情報を削除する</button>
    <%= link_to '戻る', customer_path(@customer),  style: "margin-top:5px;", class: "btn btn-default" %>
  </div>
</div>

<div class="modal fade" id="delete-customer">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">顧客情報の削除</h4>
      </div>
      <div class="modal-body">
        <p><%= @customer.family_name %>さんを削除しますか？</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">キャンセル</button>
        <%= link_to '削除する', @customer, method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/customers/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>顧客情報一覧</h1>
    <div class="row">
      <div class="col-md-6">
        <p>お客様情報が表示されます。</p>
      </div>
      <div class="col-md-6">
        <%= link_to '顧客登録', new_customer_path, class: "btn btn-default pull-right" %>
      </div>
    </div>
    
        <%= search_form_for @q do |f| %>
      <div class="row">
        <div class="col-sm-2 col-xs-12">
          <div class="form-group">
            <%= f.label :family_name_cont, '姓' %>
            <%= f.search_field :family_name_cont, class: "form-control input-sm" %>
          </div>
        </div>
        <div class="col-sm-2 col-xs-12">
          <div class="form-group">
            <%= f.label :given_name_cont, '名' %>
            <%= f.search_field :given_name_cont, class: "form-control input-sm" %>
          </div>
        </div>
        <div class="col-sm-2 col-xs-12">
          <div class="form-group">
            <%= f.label :email_cont, '電子メール' %>
            <%= f.search_field :email_cont, class: "form-control input-sm" %>
          </div>
        </div>
        <div class="col-sm-3 col-xs-12">
          <div class="form-group">
            <%= f.label :company_name_cont, '会社名' %>
            <%= f.search_field :company_name_cont, class: "form-control input-sm" %>
          </div>
        </div>
        <div class="col-sm-3 col-xs-12">
          <div class="form-group">
            <%= f.label :post_position_name_cont, '役職名' %>
            <%= f.search_field :post_position_name_cont, class: "form-control input-sm" %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 text-center">
          <%= f.submit "検索", class: "btn btn-default" %>
          <%= link_to "リセット", request.path, class:"btn btn-default" %>
        </div>
      </div>
    <% end %>

    <hr />
    
    <div class="row">
      <div class="col-md-12">
        <table class="table table-striped">
          <thead>
           <th><%= sort_link(@q, :family_name, "姓") %></th>
            <th><%= sort_link(@q, :given_name, "名") %></th>
            <th><%= sort_link(@q, :email, "電子メール") %></th>
            <th><%= sort_link(@q, :company_name, "所属会社") %></th>
            <th><%= sort_link(@q, :post_position_name, "役職") %></th>
          </thead>
          <tbody>
            <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.family_name %></td>
              <td><%= customer.given_name %></td>
              <td><%= customer.email %></td>
              <td><%= customer.company.name %></td>
              <td><%= customer.post.position_name %></td>
              <td><%= link_to '詳細', customer, class: "btn btn-default btn-xs" %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @customers %>
      </div>
    </div>
  </div>
</div>

app/views/customers/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>顧客新規登録</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/customers/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>顧客詳細</h1>
    <dl>
      <dt>お名前</dt>
      <dd style="margin:0px 0px 10px 20px"><%= @customer.full_name %></dd>
      <dt>電子メール</dt>
      <dd style="margin:0px 0px 10px 20px"><%= @customer.email %></dd>
      <dt>会社名</dt>
      <dd style="margin:0px 0px 10px 20px"><%= @customer.company.name %></dd>
      <dt>役職名</dt>
      <dd style="margin:0px 0px 10px 20px"><%= @customer.post.position_name %></dd>
    </dl>
    <%= link_to '編集', edit_customer_path(@customer), class: "btn btn-default" %>
    <%= link_to '戻る', customers_path, class: "btn btn-default" %>
  
    <hr />
  
    <h2>対応履歴</h2>
    <% @comments.each do |comment| %>
      <div class="media">
        <div class="media-body">
          <%= image_tag(comment.user.image_url, :width => "60", :align => :left ) %>
          
          <%= simple_format(comment.body) %>
          <p class="text-muted">
            投稿記事:<%= comment.created_at.strftime('%Y%m%d %H:%M') %>
            <%= link_to "削除する", comment_path(comment), method: :delete %>
          </p>
        </div>
      </div>
    <% end %>
  
    <%= image_tag(current_user.image_url, :width => "60") %>
  
    <%= form_for(@comment, url: { controller: :comments, action: :create }) do |f| %>
     <% if @comment.errors.any? %>
     <div class="alert alert-danger">
      <p><b><%= @comment.errors.count %>件のエラーがあります</b></p>
     
      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
     </div>
    <% end %>
      <div class="form-group">
        <%= f.label :body , '対応内容' %><br>
        <%= f.text_area :body, class: "form-control" %>
      </div>
      <%= f.hidden_field :customer_id, value: @customer.id %>
      <%= f.hidden_field :user_id, value: current_user.id %>

      <%= f.submit class: "btn btn-default" %>
    <% end %>
  
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-menu">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/customers">顧客管理システム</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-menu">
      <ul class="nav navbar-nav navbar-right">
       <% if user_signed_in? %>
          <li><%= link_to "設定変更", edit_user_registration_path %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ElitesCrm02</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  
</head>
<body>
<%= render partial: 'layouts/header' %>

  <div class="container">
    <% if notice.present? %>
    <div class="alert alert-dismissable alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><%= notice %></p>
    </div>
  <% end %>

  <% if alert.present? %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><%= alert %></p>
    </div>
  <% end %>
  
  <%= yield %>
  </div>
</body>
</html>